### ISSUE TITLE
"Check for new fields" on "Manage Fields" pages causes a WSOD

### ISSUE THREAD

**Issue by laceysanderson** [tripal/t4d8#296]
For any Tripal content type, the "Check for new fields" button at the top of the "Manage fields" page produces a WSOD. When you check the logs you see the following error:

```
Error: Call to a member function getTerm() on null in Drupal\tripal\Entity\TripalEntityType->getTerm() (line 232 of /var/www/drupal9/web/modules/contrib/tripal/tripal/src/Entity/TripalEntityType.php)

#0 /var/www/drupal9/web/modules/contrib/tripal/tripal/src/Controller/TripalEntityUIController.php(88): Drupal\tripal\Entity\TripalEntityType->getTerm()
#1 [internal function]: Drupal\tripal\Controller\TripalEntityUIController->tripalCheckForFields(Object(Drupal\tripal\Entity\TripalEntityType))
#2 /var/www/drupal9/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#3 /var/www/drupal9/web/core/lib/Drupal/Core/Render/Renderer.php(564): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#4 /var/www/drupal9/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#5 /var/www/drupal9/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#6 /var/www/drupal9/vendor/symfony/http-kernel/HttpKernel.php(169): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#7 /var/www/drupal9/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#8 /var/www/drupal9/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /var/www/drupal9/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /var/www/drupal9/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /var/www/drupal9/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/www/drupal9/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /var/www/drupal9/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /var/www/drupal9/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /var/www/drupal9/web/core/lib/Drupal/Core/DrupalKernel.php(709): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /var/www/drupal9/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#17 {main}
```

## Steps to Reproduce

1. Navigate to the manage fields page for an organism (or any content type) by going to Tripal > Page Structure in the admin toolbar
2. Click on the arrow beside edit for organism (3rd row) and selecting "Manage Fields" from the resulting drop down.
![Screen Shot 2022-11-02 at 2 47 45 PM](https://user-images.githubusercontent.com/1566301/199599833-b9dce1d1-b709-4e31-8c4f-498836f2452a.png)
3. Click on the "Check for new fields" button at the top of the page.
![Screen Shot 2022-11-02 at 2 49 22 PM](https://user-images.githubusercontent.com/1566301/199599872-25479da9-316f-43d4-a49c-30edbef6d6b8.png)

**Comment by laceysanderson** [comment]
This was already fixed 🎉 In so far as we now get told it's not implemented yet rather then giving us a WSOD.

<img width="1064" alt="Screen Shot 2022-12-26 at 2 16 56 PM" src="https://user-images.githubusercontent.com/1566301/209580940-53698d9c-2eae-4ded-8906-23653548dd54.png">
